name: Deploy aplications on ftp

on: push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: kartelmedia.co.uk
        username: pocztapolska@kartelmedia.co.uk
        password: ${{ secrets.FTP_PASSWORD }}
